name       : libmaxminddb
version    : 1.5.0
release    : 2
source     :
    - https://github.com/maxmind/libmaxminddb/releases/download/1.5.0/libmaxminddb-1.5.0.tar.gz : 7c56e791ff2a655215e7ed3864b1ffdd7d34a38835779efed56a42f056bd58aa
license    : Apache-2.0
component  : programming.library
summary    : C library for the MaxMind DB file format
description: |
    The libmaxminddb library provides a C library for reading MaxMind DB files, including the GeoIP2 databases from MaxMind. This is a custom binary format designed to facilitate fast lookups of IP addresses while allowing for great flexibility in the type of data associated with an address.
#builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
